apiVersion: batch/v1
kind: Job
metadata:
  name: create-registry-credentials
spec:
  template:
    spec:
      containers:
      - name: create-registry-credentials
        image: bitnami/kubectl:1.19
        command:
        - /bin/sh
        - -c
        - |
          REGISTRY_USERNAME=`tr -dc A-Za-z0-9 </dev/urandom | head -c 16 ; echo ''`
          REGISTRY_PASSWORD=`tr -dc A-Za-z0-9 </dev/urandom | head -c 16 ; echo ''`
          kubectl create secret generic registry-credentials --from-literal=username=$REGISTRY_USERNAME --from-literal=password=$REGISTRY_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
