apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-secrets
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: manage-secrets
  apiGroup: rbac.authorization.k8s.io
